FROM python:3.8-alpine
ENV APP /CurrencyBot
RUN mkdir $APP
WORKDIR $APP

COPY ./requirements_currency_bot.txt .
RUN apk add --no-cache --virtual .build-deps gcc make musl-dev libressl libffi libressl-dev libffi-dev openssl-dev
RUN pip3 install -r requirements_currency_bot.txt
RUN apk del .build-deps gcc make musl-dev

COPY .$APP/*.py ./

CMD python3 bot.py